const express = require('express');
const router = express.Router();
const userController = require('../controllers/userController');
const authMiddleware = require('../middleware/authMiddleware');
// Define user routes here
router.post('/register', userController.registerUser);
router.post('/login', userController.loginUser);
router.post('/logout', userController.logoutUser);
router.post('/reset-password', userController.resetPassword); 
router.get('/profile', authMiddleware, userController.getProfile);
router.put('/profile', authMiddleware, userController.updateProfile);
router.put('/toggle-privacy', authMiddleware, userController.togglePrivacy);
router.post('/upgrade-premium', authMiddleware, userController.upgradeToPremium);
router.put('/profile-picture', authMiddleware, userController.addProfilePicture);
router.put('/highlight-video', authMiddleware, userController.updateHighlightVideo);
//router.post('/courses', authMiddleware, userController.addCourse);
//router.post('/achievements', authMiddleware, userController.addAchievement);
router.post('/send-verification-email', userController.sendVerificationEmail);
router.post('/verify-email', userController.verifyEmail);
router.post('/check-user-exists', userController.checkUserExists);
//router.delete('/delete-user', userController.deleteUser);
router.delete('/delete-all-users', userController.deleteAllUsers);
router.get('/profilepicture', authMiddleware, userController.getProfilePicture);
router.get('/highlightvideo', authMiddleware, userController.getHighlightVideo);
router.get('/total-users', userController.getTotalUsers);
router.get('/total-premium-users', userController.getTotalPremiumUsers);
router.get('/users-growth/three-months', userController.getUsersGrowthThreeMonths);
router.get('/users-growth/year', userController.getUsersGrowthYear);
router.get('/users-growth/lifetime', userController.getUsersGrowthLifetime);
router.get('/search-players', userController.searchPlayers);
router.get('/:userId', authMiddleware, userController.getUserById);
router.post('/ban/:userId', authMiddleware, userController.banUser);
router.post('/unban/:userId', authMiddleware, userController.unbanUser);
router.delete('/:userId', authMiddleware, userController.deleteUser);
    
module.exports = router;
