const express = require('express');
const router = express.Router();
const userController = require('../controllers/userController');
const authMiddleware = require('../middleware/authMiddleware');
// Define user routes here
router.post('/register', userController.registerUser);
router.post('/login', userController.loginUser);
router.post('/logout', userController.logoutUser);
router.post('/reset-password', userController.resetPassword); 
router.get('/profile', authMiddleware, userController.getProfile);
router.put('/profile', authMiddleware, userController.updateProfile);
router.put('/toggle-privacy', authMiddleware, userController.togglePrivacy);
router.post('/upgrade-premium', authMiddleware, userController.upgradeToPremium);
router.put('/profile-picture', authMiddleware, userController.addProfilePicture);
router.put('/highlight-video', authMiddleware, userController.updateHighlightVideo);
//router.post('/courses', authMiddleware, userController.addCourse);
//router.post('/achievements', authMiddleware, userController.addAchievement);
router.post('/send-verification-email', userController.sendVerificationEmail);
router.post('/verify-email', userController.verifyEmail);
router.post('/check-user-exists', userController.checkUserExists);
router.delete('/delete-user', userController.deleteUser);
router.delete('/delete-all-users', userController.deleteAllUsers);
router.get('/profilepicture', authMiddleware, userController.getProfilePicture);
router.get('/highlightvideo', authMiddleware, userController.getHighlightVideo);
router.get('/total-users', userController.getTotalUsers);
router.get('/total-premium-users', userController.getTotalPremiumUsers);
router.get('/total-revenue', userController.getTotalRevenue);
router.get('/users-growth/three-months', userController.getUsersGrowthThreeMonths);
router.get('/users-growth/year', userController.getUsersGrowthYear);
router.get('/users-growth/lifetime', userController.getUsersGrowthLifetime);
router.get('/revenue-growth/three-months', userController.getRevenueGrowthThreeMonths);
router.get('/revenue-growth/year', userController.getRevenueGrowthYear);
router.get('/revenue-growth/lifetime', userController.getRevenueGrowthLifetime);
router.get('/premium-subscriptions/three-months', userController.getPremiumSubscriptionsThreeMonths);
router.get('/premium-subscriptions/year', userController.getPremiumSubscriptionsYear);
router.get('/premium-subscriptions/lifetime', userController.getPremiumSubscriptionsLifetime);
router.get('/premium-unsubscriptions/three-months', userController.getPremiumUnsubscriptionsThreeMonths);
router.get('/premium-unsubscriptions/year', userController.getPremiumUnsubscriptionsYear);
router.get('/premium-unsubscriptions/lifetime', userController.getPremiumUnsubscriptionsLifetime);
router.get('/search-players', userController.searchPlayers);

module.exports = router;
